# Generated by Django 2.1.5 on 2019-10-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_googlebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='LtrQueries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(default=0)),
                ('qid', models.IntegerField()),
                ('f1', models.FloatField(default=0.0, max_length=10)),
                ('f2', models.FloatField(default=0.0, max_length=10)),
                ('f3', models.FloatField(default=0.0, max_length=10)),
                ('f4', models.FloatField(default=0.0, max_length=10)),
                ('docid', models.IntegerField()),
                ('q', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('status', models.SmallIntegerField()),
            ],
        ),
    ]
